[package]
name = "tut-core"
edition = "2021"

[dependencies]
derive_more = "0.99.17"
serde = { version = "1.0.195", features = ["derive"] }
tokio = { version = "1.35.1", features = ["full"] }
tracing = "0.1.40"
uuid = { version = "1.6.1", features = ["v4", "serde"] }
